# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: bb-annotations-0.1.0dev
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - imageio
  - imageio-ffmpeg
  - importlib-metadata>=1.5.0
  - ipykernel>=5.1.1
  - IPython>=7.7.0
  - magicgui==0.2.5
  - natsort
  - numpy>=1.10
  - pandas
  - Pillow!=7.1.0,!=7.1.1  # not a direct dependency, but 7.1.0 and 7.1.1 broke imageio
  - psutil>=5.0
  - PyOpenGL>=3.1.0
  - pyside2>=5.12.3, <5.15
  - PyYAML>=5.1
  - qtconsole>=4.5.1
  - qtpy>=1.7.0
  - scipy>=1.2.0
  - scikit-image==0.17.2
  - toolz>=0.10.0
  - vispy>=0.6.4
  - wrapt>=1.11.1
  - appdirs>=1.4.4
  - cachey>=0.2.1
  - dask[array]>=2.1.0,!=2.28.0  # https://github.com/napari/napari/issues/1656
  - imageio>=2.5.0
  - importlib-metadata>=1.5.0 ; python_version < '3.8'
  - jsonschema>=3.2.0
  - napari-console>=0.0.2
  - napari-plugin-engine>=0.1.9
  - napari-svg>=0.1.4
  - numpydoc>=0.9.2
  - pydantic>=1.8.1
  - tifffile>=2020.2.16
  - typing_extensions
  - pip:
    - git+https://github.com/napari/napari.git@master#egg=napari # master

